- hosts: all
  become: yes
  become_user: root
  
  vars_files:
     - ./vms_config.yml

  roles: 
  #    - { role: roles/common }
    - { role: roles/disable-all-centos-repos }
    - { role: centos7reposerver/roles/centos7reposrv}
    - { role: centos7reposerver/roles/gpg-generate-keyring } 
    - { role: centos7reposerver/roles/centos7debreposrv } 
