reposrv:
    name: "reposrv"
    ip: "192.168.1.200"
    ssh_port: 22
    cpus: 1
    mem: 200
    box: "geerlingguy/centos7"
    playbook: "reposrv_playbook.yml"
    domain: "centos7vt.com"
    mountpoints:
         - local: /home/olip/Git/centos7vt2-vagrant-boxes/centos7reposerver/rpms/
           remote: /var/www/html/repository/centos/

lab_machines:
  - name: "master"
    ip: "192.168.1.100"
    ssh_port: 22
    cpus: 1
    mem: 200
    box: "geerlingguy/centos7"
    playbook: "centos_playbook.yml"
    domain: "centos7vt.com"
  
  - name: "client1"
    ip: "192.168.1.101"
    ssh_port: 22
    cpus: 1
    mem: 200
    box: "geerlingguy/centos7"
    playbook: "centos_playbook.yml"
    domain: "centos7vt.com"
  
  - name: "client2"
    ip: "192.168.1.102"
    ssh_port: 22
    cpus: 1
    mem: 200
    box: "geerlingguy/centos7"
    playbook: "centos_playbook.yml"
    domain: "centos7vt.com"
 
  - name: "slave"
    ip: "192.168.1.103"
    ssh_port: 22
    cpus: 1
    mem: 200
    box: "geerlingguy/centos7"
    playbook: "centos_playbook.yml"
    domain: "centos7vt.com"

  - name: "ubuntubox"
    ip: "192.168.1.50"
    ssh_port: 22
    cpus: 1
    mem: 200
    box: "ubuntu/trusty64"
    playbook: "ubuntu_playbook.yml"
    domain: "centos7vt.com"

