lab_machines:
  - name: "master"
    ip: "192.168.2.100"
    ssh_port: 22
    cpus: 1
    mem: 200
    box: "jasonc/centos7-32bit"
    playbook: "centos_playbook.yml"
    domain: "centos7vt.com"
  
  - name: "client1"
    ip: "192.168.2.101"
    ssh_port: 22
    cpus: 1
    mem: 200
    box: "jasonc/centos7-32bit"
    playbook: "centos_playbook.yml"
    domain: "centos7vt.com"
  
  - name: "client2"
    ip: "192.168.2.102"
    ssh_port: 22
    cpus: 1
    mem: 200
    box: "jasonc/centos7-32bit"
    playbook: "centos_playbook.yml"
    domain: "centos7vt.com"
 
  - name: "slave"
    ip: "192.168.2.103"
    ssh_port: 22
    cpus: 1
    mem: 200
    box: "jasonc/centos7-32bit"
    playbook: "centos_playbook.yml"
    domain: "centos7vt.com"

  - name: "ubuntubox"
    ip: "192.168.2.50"
    ssh_port: 22
    cpus: 1
    mem: 200
    box: "ubuntu/trusty64"
    playbook: "ubuntu_playbook.yml"
    domain: "centos7vt.com"

