# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

lab_machines = {
  "instructor"  => { :ip => "192.168.1.100", :cpus => 1, :mem => 200 },
}

Vagrant.configure("2") do |config|

# like global settings valid for all machines
   config.vm.provider "virtualbox"
  # config.vm.box = "centos/7"
   config.vm.box = "ubuntu/trusty64"
   config.ssh.insert_key = false

   lab_machines.each_with_index do |(hostname, infos), index|
    config.vm.define "#{hostname}" do |machine|
      machine.vm.network "private_network", ip: "#{infos[:ip]}"
      if index == lab_machines.size - 1
   	 machine.vm.provision :ansible do |ansible|
	   ansible.limit = "all"
           ansible.playbook = "playbook.yml"
	   ansible.inventory_path = "inventory"
	 end
      end
      machine.vm.provider "virtualbox" do |vb|
          vb.customize ["modifyvm", :id, "--memory", "#{infos[:mem]}"]
	  vb.customize ["modifyvm", :id, "--cpus", "#{infos[:cpus]}"]
      end
    end
   end
end
